name: Deploy MeetApp app

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  id-token: write
  pages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "19"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
